### ISSUE TITLE
Support for 1.17

### ISSUE THREAD

**Issue by louanfontenele** [AlonsoAliaga/BetterBackpacks#2]
![image](https://user-images.githubusercontent.com/2886066/125183465-29388200-e1ed-11eb-8f3c-b39aa99dee6e.png)

Please, add support to 1.17

**Comment by AlonsoAliaga** [comment]
Seems that something changed between 1.16 and 1.17, for now it cannot be updated.
(These are news from my discord server and spigot profile)
- I'm currently recovering from a surgery
- Working on delayed university homework (bc of surgery)
- And after finishing that, I have a queue of pending plugins which requires updates (from most used or easy to update, to less used or harder to update)
Currently updating this plugin requires many try and error playing with spigot internal methods, time that sadly I don't have for now.
I'll try to update it once I'm able to, hope you understand

**Comment by louanfontenele** [comment]
> Seems that something changed between 1.16 and 1.17, for now it cannot be updated.
> (These are news from my discord server and spigot profile)
> 
> * I'm currently recovering from a surgery
> * Working on delayed university homework (bc of surgery)
> * And after finishing that, I have a queue of pending plugins which requires updates (from most used or easy to update, to less used or harder to update)
>   Currently updating this plugin requires many try and error playing with spigot internal methods, time that sadly I don't have for now.
>   I'll try to update it once I'm able to, hope you understand

Of course I understand, I hope you get better from your surgery, and hope you do update the plugin, it is without doubt the best in this category of Backpacks.

**Comment by AlonsoAliaga** [comment]
✅ **1.17.x support has been added in 0.7-BETA!**

Thanks for your patient 😉
