### ISSUE TITLE
backpacks disappearing on v0.8-beta

### ISSUE THREAD

**Issue by NotAShelf** [AlonsoAliaga/BetterBackpacks#3]
**Describe the bug**
Backpacks disappearing

**To Reproduce**
I'm not sure on how exactly this is reproduced as it is hard to explain, but there is a video below to demonstrate the error.

**Expected behavior**
The backpack shouldn't disappear.

**Screenshots**
I do not have any screenshots, but my player has recorded this video to better demonstrate this problem.
[Link to youtube video](https://youtu.be/IsClCwSqSTo)

**Important:**
 - Java version: 16
 - Plugin version: 0.8-beta
 - Server version: git-purpur-1303

**Additional context**
n/a

P.S: I didn't test other plugin version but this is most likely not exclusive to v0.8-beta

**Comment by AlonsoAliaga** [comment]
Hello, please join my server on https://alonsoaliaga.com/discord so we can talk faster

**Comment by NotAShelf** [comment]
joined

**Comment by AlonsoAliaga** [comment]
**Fixed in 0.9-BETA (Pending to release)**
